// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/home": {
    params: {};
  };
  "/home/timetable": {
    params: {};
  };
  "/home/chatbot": {
    params: {};
  };
  "/home/flashcard": {
    params: {};
  };
  "/home/collaboration": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/home" | "/home/timetable" | "/home/chatbot" | "/home/flashcard" | "/home/collaboration";
  };
  "loginAuth/login.tsx": {
    id: "loginAuth/login";
    page: "/";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/home" | "/home/timetable" | "/home/chatbot" | "/home/flashcard" | "/home/collaboration";
  };
  "routes/dashboard.tsx": {
    id: "routes/dashboard";
    page: "/home";
  };
  "routes/timetable.tsx": {
    id: "routes/timetable";
    page: "/home/timetable";
  };
  "routes/chatbot.tsx": {
    id: "routes/chatbot";
    page: "/home/chatbot";
  };
  "routes/flashcard.tsx": {
    id: "routes/flashcard";
    page: "/home/flashcard";
  };
  "routes/collaboration.tsx": {
    id: "routes/collaboration";
    page: "/home/collaboration";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "loginAuth/login": typeof import("./app/loginAuth/login.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/dashboard": typeof import("./app/routes/dashboard.tsx");
  "routes/timetable": typeof import("./app/routes/timetable.tsx");
  "routes/chatbot": typeof import("./app/routes/chatbot.tsx");
  "routes/flashcard": typeof import("./app/routes/flashcard.tsx");
  "routes/collaboration": typeof import("./app/routes/collaboration.tsx");
};